apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: utsjekk-unleash-api-token
  namespace: helved
  labels:
    team: helved
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: helved
  secretName: utsjekk-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: development 

