apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: {{unleash.apiToken}}
  namespace: helved
  labels:
    team: helved
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: helved
  secretName: {{unleash.apiToken}}

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{unleash.environment}}