name: build & deploy - utsjekk-oppdrag

on:
  workflow_dispatch:
#  push:
#    paths:
#      - 'apps/utsjekk/**'
#      - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew apps:utsjekk:test apps:utsjekk:buildFatJar --continue --no-daemon

      - uses: nais/docker-build-push@v0
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ github.sha }}
          docker_context: ./apps/utsjekk
          dockerfile: ./apps/utsjekk/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: dev-gcp
          RESOURCE: apps/utsjekk/application-dev.yml
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}/utsjekk:${{ github.sha }}
