name: oppdrag

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/oppdrag/**'
      - 'libs/**'

jobs:
  build:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write  # submit dependency-graph
      id-token: write  # publish docker image
      actions: read    #
      checks: write    # write test results
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit

      - run: ./gradlew apps:oppdrag:test apps:oppdrag:buildFatJar --continue --no-daemon --parallel

      - uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: tests
          path: "**/**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: oppdrag
          tag: ${{ github.sha }}
          docker_context: ./apps/oppdrag
          dockerfile: ./apps/oppdrag/Dockerfile

  deploy-dev:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    permissions:
      contents: read    # read repository files
      id-token: write   # publish nais manifest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: dev-gcp
          RESOURCE: apps/oppdrag/application-dev.yml
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}-oppdrag:${{ github.sha }}

#  deploy-prod:
#    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    needs: build
#    permissions:
#      contents: read    # read repository files
#      id-token: write   # publish nais manifest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: nais/login@v0
#        id: login
#        with:
#          team: helved
#          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
#          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
#      - uses: nais/deploy/actions/deploy@v2
#        env:
#          PRINT_PAYLOAD: true
#          CLUSTER: prod-gcp
#          RESOURCE: apps/oppdrag/application-prod.yml
#          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}-oppdrag:${{ github.sha }}
